### ISSUE TITLE
fetch-examples-ml5 examples testing

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/p5.js-web-editor#1]
## About 
Testing to see which examples are working using the fetch-ml5-examples script:
https://github.com/joeyklee/p5.js-web-editor/blob/fetch-ml5-examples/server/scripts/examples-ml5.js 

## steps to reproduce:
1. clone this fork
2. npm install
3. npm run fetch-examples-ml5
4. (if you run into github api request limits, you should run the following)
5. `$ GITHUB_ID=<....> GITHUB_SECRET=<...> NODE_ENV=development npm run fetch-examples-ml5` where the GITHUB_ID and GITHUB_SECRET are the alphanumeric character strings created in your `Github personal access tokens`

## Check the examples that are working
- [ ] CharRNN_Interactive
	- [ ] Chrome: `Refused to execute script from 'https://raw.githubusercontent.com/ml5js/ml5-examples/release/p5js/CharRNN/CharRNN_Text/sketch.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`
	- [ ] Firefox:
- [ ] CharRNN_Text
	- [ ] Chrome: `Refused to execute script from 'https://raw.githubusercontent.com/ml5js/ml5-examples/release/p5js/CharRNN/CharRNN_Text/sketch.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`
	- [ ] Firefox:
- [ ] CharRNN_Text_Stateful
	- [ ] Chrome: `Refused to execute script from 'https://raw.githubusercontent.com/ml5js/ml5-examples/release/p5js/CharRNN/CharRNN_Text/sketch.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`
	- [ ] Firefox:
- [ ] FeatureExtractor_Image_Classification
	- [x] Chrome: ✅
	- [ ] Firefox:
- [ ] FeatureExtractor_Image_Regression
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification_MultipleImages
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification_Video
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification_VideoScavengerHunt
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification_VideoSound
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] ImageClassification_VideoSoundTranslate
	- [ ] Chrome:
	- [ ] Firefox:
- [ ] KNNClassification_PoseNet
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] KNNClassification_Video
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] KNNClassification_VideoSound
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] KNNClassification_VideoSquare
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] PitchDetection
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] PitchDetection_Game
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] PitchDetection_Piano
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] Pix2Pix_callback
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] Pix2Pix_promise
	- [ ] Chrome: ```VM8946 about:srcdoc:127 Uncaught TypeError: ml5.pix2pix(...).then is not a function
    at drawImage (VM8758 about:srcdoc:127)
    at Image.i.onload (VM8851 p5.min.js:3)```
	- [ ] Firefox:
- [ ] PoseNet_image_single
	- [ ] Chrome: ```tf-core.esm.js:17 Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.```
	- [ ] Firefox:
- [ ] PoseNet_part_selection
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] PoseNet_webcam
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] SketchRNN_basic
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] SketchRNN_interactive
	- [x] Chrome:✅
	- [ ] Firefox:
- [ ] StyleTransfer_Image
	- [ ] Chrome: ```tf-core.esm.js:17 Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.```
	- [ ] Firefox:
- [ ] StyleTransfer_Video
	- [x] Chrome:✅
	- [ ] Firefox:
             ```
            Unhandled promise rejection TypeError: "img is undefined"

            gotResult about:srcdoc:73 ml5 0.2.3/dist/ml5.min.js:58 ml5 0.2.3/dist/ml5.min.js:106 ml5/0.2.3/dist/ml5.min.js:106 ml5 0.2.3/dist/ml5.min.js:106 

            previewScripts.js:15478:13
            Unhandled promise rejection Error: "Requested texture size [0x0] is invalid."
             ```
- [ ] data
	- [ ] Chrome:
	- [ ] Firefox:
- [ ] YOLO_single_image
	- [ ] Chrome: 
               ```
tf-core.esm.js:17 Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:94133
    at on (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:84726)
    at Xn (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:94108)
    at e.uploadPixelDataToTexture (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:100383)
    at e.fromPixels (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:140619)
    at e.fromPixels (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:35556)
    at fromPixels_ (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:132653)
    at Object.fromPixels (https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:52960)
    at https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:58:48786
    at https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:18:27758
               ```
	- [ ] Firefox:
               ```
               Unhandled promise rejection DOMException: "The operation is insecure."
               ```
- [ ] YOLO_webcam
	- [x] Chrome:✅
	- [ ] Firefox:
              ```
               Unhandled promise rejection e/</<@https://unpkg.com/ml5@0.2.3/dist/ml5.min.js:90:136693
              ```

**Comment by shiffman** [comment]
Wonderful! I'll note a couple of "known issues" here as context. 

* Image uploads fail with ml5 image classification / feature extractor examples. (see: https://github.com/ml5js/ml5-examples/issues/6)
* Web editor does not have support for  file formats that store weights (`.bin`, etc.) for loading models (easy one?) 

There might be more these are two off the top of my head!

**Comment by joeyklee** [comment]
@shiffman - thanks so much! I'll start going through and seeing what happens.
